## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
server:
  port: 8083
spring:
  datasource:
      url: jdbc:postgresql://localhost:5432/shreyas
      username : shreyas
      password : shreyas
  jpa:
    properties:
      hibernate:
        dialect : org.hibernate.dialect.PostgreSQLDialect
        ddl-auto : update

  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS : false
    time-zone : UTC